name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint markdownlint-cli

    - name: Check code formatting with black
      run: black --check your_script.py

    - name: Lint Python code with pylint
      run: pylint your_script.py

    - name: Lint Markdown files with markdownlint
      run: markdownlint **/*.md
